### ISSUE TITLE
Add support for geospatial-path-indexes, and geospatial-region-path-indexes

### ISSUE THREAD

**Issue by tdiepenbrock** [marklogic-community/roxy#863] opened 2017-12-01 18:29 UTC
This is related to issue #850 

#### The issue

Short description of the problem:

What are the steps to reproduce the problem?
1. Create a database with one of the indexes described in the title
2. Bootstrap
3. Bootstrap again

#### Tech Specs

Which Operating System are you using?

RHEL 7.x

Which version of MarkLogic are you using?

9.0-3.1

Which version of Roxy are you using (see version.txt)?

1.7.7

**Comment by grtjn** [comment] 2017-12-01 19:07
Sounds like basically a dupe of #850. Need the fix soon rather than late?

**Comment by tdiepenbrock** [comment] 2017-12-01 19:16
I submitted the fix in a pull request, looks like there are some conflicts to resolve, however.

td


Thomas Diepenbrock
Technical Manager
MarkLogic Corporation
Thomas.Diepenbrock@marklogic.com<mailto:Thomas.Diepenbrock@marklogic.com>
Cell:  +1 703 980 1248

[cid:0B48B25A-8630-42FD-BFB9-3092CB213523] <http://www.marklogic.com/social/>
<http://www.marklogic.com/social/>

On Dec 1, 2017, at 2:07 PM, Geert <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds like basically a dupe of #850<https://github.com/marklogic-community/roxy/issues/850>. Need the fix soon rather than late?

**Comment by grtjn** [comment] 2018-01-10 08:50
I changed the title of this ticket to reflect the addition of geo path index support. Metadata fields are covered in #834, the issue with path namespaces in #850..

**Comment by grtjn** [comment] 2018-01-10 08:50
Fixed in dev

**Closed by grtjn** 2018-01-10 08:50 UTC
